FROM node:20-slim
WORKDIR /docs
RUN apt-get update && apt-get install -y \
    build-essential \
    python3 \
    && rm -rf /var/lib/apt/lists/*
COPY documentation/area-documentation ./
RUN npm install --unsafe-perm=true
EXPOSE 3000
CMD ["npm", "run", "start"]