FROM --platform=linux/amd64 ghcr.io/cafe-sur-cour/area-mobile:latest

WORKDIR /app

# Copy the APK to the volume when container starts
CMD ["sh", "-c", "cp /app/build/area.apk /app/build/area.apk && sleep infinity"]
