version: '3.8'

services:
  frontend:
    build:
      context: ..
      dockerfile: deployment/Dockerfile.frontend
    container_name: area_web
    ports:
      - "${NEXT_PORT}:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    depends_on:
      - backend
      - db

  backend:
    build:
      context: ..
      dockerfile: deployment/Dockerfile.backend
    container_name: area_app
    ports:
      - "${NODE_PORT}:3000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - FRONTEND_URL=${FRONTEND_URL}
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: postgres_area_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ../database/table/:/docker-entrypoint-initdb.d/tables/
      - ../database/relation/:/docker-entrypoint-initdb.d/relations/
      - ../database/init-postgres.sh:/docker-entrypoint-initdb.d/init-postgres.sh:ro

volumes:
  pgdata:
