name: Deploy via SSH
on:
  # push:
  push: {}
    # branches:
    #   - main
  workflow_dispatch:

    inputs:
      environment:
        description: 'Deployment environment'
        required: false
        default: 'production'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: PIPELINE
    steps:
      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: bash -c "source ~/.bashrc && deployScript.sh"